apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-ichj
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-ichj
    app.kubernetes.io/part-of: integ-app-ppaz
  name: hacbs-test-project-ichj
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-ichj
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-ichj
    spec:
      containers:
      - image: quay.io/rycole-appstudio/integration1-pjty-tenant/integ-app-ppaz/hacbs-test-project-ichj@sha256:cb6f46ae7f66e3b71a318de0ba3a89fc3eb6c6719e9dc7c541c142dce8d41aae
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 50m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 25Mi
status: {}
